module.exports = {
  singleQuote: true,
  parser: 'babel',
  trailingComma: 'all',
  arrowParens: 'avoid',
  bracketSpacing: true,
  printWidth: 100,
  insertPragma: false,
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  requirePragma: false,
  semi: true,
  tabWidth: 2,
  useTabs: false,
};
