apiVersion: v1
kind: List

items:
- kind: ConfigMap
  apiVersion: v1

  metadata:
    name: traefik-cfg
    namespace: kube-system
    labels:
      k8s-app: traefik-ingress-controller

  data:
    traefik.toml: |
      debug = false

      logLevel = "ERROR"
      defaultEntryPoints = ["https","http"]

      [entryPoints]
        [entryPoints.http]
        address = ":80"
        [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]

      [web]

      [retry]

      [kubernetes]

      [acme]
      email = "aaiello@gmail.com"
      storage = "/data/acme.json"
      entryPoint = "https"
      onHostRule = true
      acmeLogging = true
      [acme.httpChallenge]
      entryPoint = "http"

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: traefik-ingress-controller
    labels:
      k8s-app: traefik-ingress-controller

  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - secrets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: traefik-ingress-controller
    namespace: kube-system
    labels:
      k8s-app: traefik-ingress-controller

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: traefik-ingress-controller
    labels:
      k8s-app: traefik-ingress-controller
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: traefik-ingress-controller
  subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: kube-system

- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: traefik-ingress-controller
    namespace: kube-system

    labels:
      k8s-app: traefik-ingress-controller

  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        k8s-app: traefik-ingress-controller
    template:
      metadata:
        labels:
          k8s-app: traefik-ingress-controller
      spec:
        volumes:
        - name: traefik-cfg
          configMap:
            name: traefik-cfg
        - name: data-volume
          emptyDir: {}

        initContainers:
        - name: init
          image: busybox
          command:
          - sh
          args:
          - -c
          - touch /data/acme.json && chmod 600 /data/acme.json
          volumeMounts:
          - name: data-volume
            mountPath: /data


        containers:
        - name: traefik
          image: traefik:1.6-alpine
          imagePullPolicy: Always

          args:
          - -c
          - /etc/traefik/traefik.toml
          - --kubernetes

          ports:
          - containerPort: 80
            hostPort: 80
            name: http
            protocol: TCP

          - containerPort: 443
            hostPort: 443
            name: https
            protocol: TCP

          - containerPort: 8080
            hostPort: 8080
            name: admin
            protocol: TCP

          resources:
            limits:
              cpu: 100m
              memory: 64Mi

          volumeMounts:
          - name: data-volume
            mountPath: /data
          - name: traefik-cfg
            mountPath: /etc/traefik

        restartPolicy: Always
        serviceAccount: traefik-ingress-controller
        serviceAccountName: traefik-ingress-controller

        nodeSelector:
          kubernetes.io/lb: "true"
